### PR TITLE
Add appdata.xml for publishing on e.g. Flathub

### PR DESCRIPTION
**Pull request by Newbytee**
Very much inspired by Pure Maps' appdata.xml: https://github.com/rinigus/pure-maps/blob/4137df935bef31663a3d3aa7c5f640c80135d3fe/packaging/pure-maps.appdata.xml

~~It is missing a content rating and a metadata licence. I'm not quite sure what to put there. Feedback welcome! Also, I only included the latest release in releases. If you prefer I can add in all the old ones, but I decided against doing that for now.~~

Related: https://github.com/mirukana/mirage/issues/1

### CODE REVIEW

**Comment by RezurrectBodg** [comment]
Well, content rating is 0+, obviously.

**Comment by Newbytee** [comment]
> Well, content rating is 0+, obviously.

Hmm, are you sure? You could find mostly anything on Matrix.

**Comment by Newbytee** [comment]
This is apparently where you should go to generate a content rating: https://hughsie.github.io/oars/generate.html

I think more or less all of these things are things you *could* see on Matrix, not necessarily saying that you will, but still. Not quite sure where to take this question, but as I start I asked where I can ask questions like this in #flatpak on Freenode.

**Comment by Newbytee** [comment]
This is how Telegram does it: https://github.com/telegramdesktop/tdesktop/blob/dev/lib/xdg/telegramdesktop.appdata.xml.in#L36

It looks like they only put social stuff to intense, which makes sense as "uncontrolled chat functionality" would describe what Matrix allows for. I'll do it like they do and update this PR.

**Comment by Newbytee** [comment]
Done. Now it's just the metadata licence.

**Comment by Newbytee** [comment]
Draft because it doesn't pass validation:

```
[neboula@shock packaging]$ appstream-util validate mirage.appdata.xml 
mirage.appdata.xml: FAILED:
• tag-missing           : <metadata_license> is not present
• attribute-invalid     : <screenshot> width (283) too small [https://raw.githubusercontent.com/mirukana/mirage/master/docs/screenshots/06-chat-small.png] minimum is 624px
• attribute-invalid     : <screenshot> width (283) too small [https://raw.githubusercontent.com/mirukana/mirage/master/docs/screenshots/05-main-pane-small.png] minimum is 624px
• attribute-invalid     : <screenshot> width (283) too small [https://raw.githubusercontent.com/mirukana/mirage/master/docs/screenshots/07-room-pane-small.png] minimum is 624px
Validation of files failed
```

**Comment by mirukana** [comment]
Thanks for working on this!
The [FSFAP](https://spdx.org/licenses/FSFAP.html) looks fine for this kind of file, it's short and to the point.
I will update the old screenshots from the README soon, to better represent the current version and fit the width requirement.

We need a python script (using mistune and lxml) to automatically generate release tags from the CHANGELOG.md, last thing we want is to duplicate efforts and have to manually format all that XML for every change, let me know if you can work on it.

**Comment by Newbytee** [comment]
> We need a python script (using mistune and lxml) to automatically generate release tags from the CHANGELOG.md, last thing we want is to duplicate efforts and have to manually format all that XML for every change, let me know if you can work on it.

Sure, I'll give it a shot.

**Comment by Newbytee** [comment]
> We need a python script (using mistune and lxml) to automatically generate release tags from the CHANGELOG.md, last thing we want is to duplicate efforts and have to manually format all that XML for every change, let me know if you can work on it.

I pushed an initial draft of this. It currently only prints the result to stdout and only makes an XML that I think should be valid to be used in the appdata XML, but it doesn't validate with the following error:
```
[neboula@shock mirage]$ appstream-util validate packaging/mirage.appdata.xml 
packaging/mirage.appdata.xml: failed to parse packaging/mirage.appdata.xml: Error on line 91 char 2: <p> already set 'replacing the previous' and tried to replace with ',
see the
'
```
I will look into this more later, but if anyone has any ideas let me hear. To reproduce, copy the output from `refresh-changelog.py` and paste it between `<releases>` and `</releases>` in mirage.appdata.xml.

**Comment by Newbytee** [comment]
@mirukana The releases tag is optional: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

Would you be okay if I ditch it in this one and handle that in a later one? I can put my WIP code in a branch in my fork if someone wants to mess with it.

**Comment by mirukana** [comment]
That works too. You can copy this branch in its current state to another branch, update this one to have the file without release tags or WIP script, and I'll merged as soon as I update the screenshots.

**Comment by Newbytee** [comment]
WIP code can be found here: https://github.com/Newbytee/mirage/tree/appdata-releases

**Comment by Newbytee** [comment]
Apparently it's "not optional on Flathub". Back to work then.

**Comment by Newbytee** [comment]
```
[neboula@shock packaging]$ flatpak run org.freedesktop.appstream-glib validate mirage.appdata.xml
mirage.appdata.xml: FAILED:
• tag-missing           : <release> required
Validation of files failed
```

So Flathub's Appstream XML validator doesn't mind the image sizes, but it does require at least one release to be present.

**Comment by Newbytee** [comment]
It seems like Flathub is okay with just having a releases that that contains releases and not changelogs, so let's do that.

The code isn't super pretty. I initially attempted to use Python's built-in `xml.etree.cElementTree`, but this is apparently [deprecated since Python 3.3](https://docs.python.org/3/library/xml.etree.elementtree.html) so let's not do that. I then tried lxml, but it doesn't like Unicode it seems:

ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

So I ended up with pure string manipulation plus regex and it works well from what I can tell. This validates with Flathub's Appstream Util as well:

    [neboula@shock mirage]$ flatpak run org.freedesktop.appstream-glib validate packaging/mirage.appdata.xml
    packaging/mirage.appdata.xml: OK

I understand if you don't like my approach here, and I can change it if desired. But it works!

**Pull request merged**
