### PR TITLE
Improve Python 3.9 compatibility

### LINKED ISSUE #148: Blist fails to build on python3.9
One of mirage's dependencies fails to build on python3.9.

However looking at the [repository](https://github.com/DanielStutzbach/blist/issues/90), blist has not been updated since 2014 so maybe it's a good idea to drop this dependency?

### PR DESCRIPTION
**Pull request by travankor**
Blist has been unmaintained for 5+ years and is now broken on Python 3.9.

Tested for a bit and I can't really see a performance drop.

fixes #148

### CODE REVIEW

**Comment by mirukana** [comment]
I'll have to test this with the largest matrix rooms. The constant need for insertions and removal in the middle of the model (a `O(n)` operation with the builtin `list`) to keep it sorted, might be problematic when rooms have dozens of thousands of members, especially when using the filter field which needs to perform without any major delay.

**Comment by travankor** [comment]
>The constant need for insertions and removal in the middle of the model (a O(n) operation with the builtin list) to keep it sorted

I added another commit that uses a sorted container type library. Unlike blist, this one is quite popular and looks like it will be maintained. Also seems like synapse already uses this library, which should make packaging easier.

It's not yet ready though since it has a traceback when I start it. I tried changing some lines to match the API, but I didn't really understand the existing code.

**Comment by mirukana** [comment]
Sorted Containers has important [requirements](http://www.grantjenks.com/docs/sortedcontainers/introduction.html#caveats) to work properly. I reworked `ModelItem` and updated the `items.py` classes to (hopefully) guarantee total ordering.

**Comment by mirukana** [comment]
I haven't encountered any error since the last commit, so I'll merge this to dev for now, thanks.

**Pull request merged**
